/** Short focus / discipline lines shown quietly on the timer screen. */
export const QUOTES: string[] = [
  "The secret of getting ahead is getting started.",
  "Focus is a matter of deciding what things you're not going to do.",
  "You don't have to be great to start, but you have to start to be great.",
  "Discipline is choosing between what you want now and what you want most.",
  "Deep work is the ability to focus without distraction on a hard thing.",
  "Small daily improvements are the key to staggering long-term results.",
  "Motivation gets you going, but discipline keeps you growing.",
  "Where focus goes, energy flows.",
  "Do the hard work when no one is watching.",
  "One hour of focus beats a whole day of distraction.",
  "It always seems impossible until it's done.",
  "The successful warrior is the average person, with laser-like focus.",
  "What we do every day matters more than what we do once in a while.",
  "Concentrate all your thoughts upon the work at hand.",
  "Slow is smooth, and smooth is fast.",
  "Amateurs sit and wait for inspiration; the rest of us just show up.",
  "You will never always be motivated, so you must learn to be disciplined.",
  "The best way to get something done is to begin.",
  "Starve your distractions, feed your focus.",
  "A river cuts through rock not by power, but by persistence.",
  "Done is better than perfect.",
  "The only way to do great work is to love what you do.",
  "Action is the antidote to anxiety.",
  "You do not rise to the level of your goals; you fall to the level of your systems.",
  "The obstacle is the way.",
  "Simplicity is the ultimate sophistication.",
  "Progress, not perfection.",
  "Consistency beats intensity.",
  "A goal without a plan is just a wish.",
  "Every master was once a disaster.",
  "The pain of discipline weighs ounces; the pain of regret weighs tons.",
  "Clarity comes from engagement, not thought.",
  "Willpower is like a muscle; the more you use it, the stronger it gets.",
  "The chains of habit are too light to be felt until they are too heavy to be broken.",
  "You can't build a reputation on what you're going to do.",
  "Energy flows where attention goes.",
  "Never mistake motion for action.",
  "What gets measured gets managed.",
  "The expert in anything was once a beginner.",
  "Comfort is the enemy of progress.",
  "Distraction is the death of productivity.",
  "Do today what others won't, so tomorrow you can do what others can't.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Focus on being productive instead of busy.",
  "Great things are done by a series of small things brought together.",
  "The journey of a thousand miles begins with a single step.",
  "Success is the sum of small efforts, repeated day in and day out.",
  "You miss 100% of the shots you don't take.",
  "Perfection is not attainable, but if we chase perfection we can catch excellence.",
  "Either you run the day, or the day runs you.",
  "Nothing will work unless you do.",
  "Focus is about saying no.",
  "Don't wait. The time will never be just right.",
  "You will never 'find' time for anything. If you want time, you must make it.",
  "Either you run the day, or the day runs you.",
  "Lack of direction, not lack of time, is the problem.",
  "Hard work beats talent when talent doesn't work hard.",
  "Being busy is not the same as being productive.",
  "Discipline equals freedom.",
  "It is not enough to be busy; so too are the ants. The question is: what are we busy about?",
  "Success is nothing more than a few simple disciplines, practiced every day.",
  "The pain of discipline is far less than the pain of regret.",
  "You can worry about the competition, or you can focus on what's ahead of you and drive fast.",
  "A year from now you may wish you had started today.",
  "Someday is not a day of the week.",
  "Multitasking is merely the opportunity to screw up more than one thing at a time.",
  "You can do anything, but not everything.",
  "Efficiency is doing things right; effectiveness is doing the right things.",
  "Work hard in silence, let your success be your noise.",
  "Start where you are. Use what you have. Do what you can.",
  "The way to get started is to quit talking and begin doing.",
  "Energy and persistence conquer all things.",
  "Lost time is never found again.",
  "When you silence the noise, your dreams begin to come into focus.",
];

/** A random quote, avoiding an immediate repeat of `exclude` when possible. */
export function randomQuote(exclude?: string): string {
  if (QUOTES.length <= 1) return QUOTES[0];
  let q = QUOTES[Math.floor(Math.random() * QUOTES.length)];
  while (q === exclude) q = QUOTES[Math.floor(Math.random() * QUOTES.length)];
  return q;
}
