apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: focusarc-data
  namespace: focusarc
  labels:
    app: focusarc
    role: data
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
